#!/usr/bin/env python3
"""Stage5E animation with ALL 24 SMPL joints (including hands, root)."""
import sys, numpy as np
from pathlib import Path
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

# SMPL 24-joint skeleton — ALL bones including hands
# 0-indexed SMPL joint pairs (parent, child)
BONES_24 = [
    # Spine/trunk
    (0, 1), (0, 2), (0, 3),   # pelvis → hips, spine1
    (3, 6), (6, 9),             # spine1 → spine2 → spine3
    (9, 12), (12, 15),          # spine3 → neck → head
    # Left leg
    (1, 4), (4, 7), (7, 10),   # L_hip → L_knee → L_ankle → L_foot
    # Right leg
    (2, 5), (5, 8), (8, 11),   # R_hip → R_knee → R_ankle → R_foot
    # Left arm
    (9, 13), (13, 16), (16, 18), (18, 20), (20, 22),  # spine3 → collar → shoulder → elbow → wrist → HAND
    # Right arm
    (9, 14), (14, 17), (17, 19), (19, 21), (21, 23),  # spine3 → collar → shoulder → elbow → wrist → HAND
]

# Joint names for all 24 SMPL joints
JOINT_NAMES_24 = [
    "pelvis",        # 0
    "L_hip",         # 1
    "R_hip",         # 2
    "spine1",        # 3
    "L_knee",        # 4
    "R_knee",        # 5
    "spine2",        # 6
    "L_ankle",       # 7
    "R_ankle",       # 8
    "spine3",        # 9
    "L_foot",        # 10
    "R_foot",        # 11
    "neck",          # 12
    "L_collar",      # 13
    "R_collar",      # 14
    "head",          # 15
    "L_shoulder",    # 16
    "R_shoulder",    # 17
    "L_elbow",       # 18
    "R_elbow",       # 19
    "L_wrist",       # 20
    "R_wrist",       # 21
    "L_hand",        # 22  ← PREVIOUSLY EXCLUDED!
    "R_hand",        # 23  ← NOW GENERATED BY MODEL
]


def main():
    device = "cpu"
    import stage5e_per_joint_10base_mdn as s5e
    from smpl_fk import fk_smpl_full

    # Load data (now 24 joints, 75-d)
    data, n_joints = s5e.load_amass_pose_body(
        "C:/Dropbox/projects/AGI_visualize_humanmotion/data/amass_npz",
        n_files=200, n_frames=96, seed=42)
    print(f"Loaded {len(data)} walks ({n_joints} joints)")

    # Pick a good walk
    good_walk_files = ['walking_medium01_stageii.npz', 'walk_6m_straight_line04_stageii.npz']
    good_data = None
    for fname in good_walk_files:
        for f in Path('C:/Dropbox/projects/AGI_visualize_humanmotion/data/amass_npz').rglob(fname):
            d = np.load(f, allow_pickle=True)
            idx = np.linspace(0, d['pose_body'].shape[0]-1, 96, dtype=int)
            ro = d['root_orient'][idx]
            pb = d['pose_body'][idx]
            tr = d['trans'][idx]
            hand_z = np.zeros((96, 6), dtype=np.float32)
            full_rot = np.concatenate([ro, pb, hand_z], axis=1)  # (96, 72)
            good_data = np.concatenate([full_rot, tr], axis=1)   # (96, 75)
            print(f"Test: {f.name}")
            break
        if good_data is not None:
            break

    rng = np.random.default_rng(43)
    perm = rng.permutation(len(data))

    # Base from N_BASE RANDOM walks (not fixed first-N — samples diverse styles)
    N_BASE = 20
    rng_base = np.random.default_rng()  # fresh seed each run → truly random selection
    base_idx = rng_base.choice(len(data), N_BASE, replace=False)
    base_data = data[base_idx]
    rot_base = base_data[:, :, :72].reshape(N_BASE, 96, n_joints, 3)
    bases_rot = s5e.compute_per_joint_mean_bases(
        rot_base.reshape(N_BASE, 96, -1), n_base_walks=N_BASE)

    # Train — use remaining samples
    train_mask = np.ones(len(data), dtype=bool)
    train_mask[base_idx] = False
    train_data = data[train_mask][:150]

    model = s5e.PerJointRotationMDN(n_joints=n_joints, n_timesteps=96,
                                     n_components=4, feature_dim=32, hidden_dim=128).to(device)

    print(f"Training ({len(train_data)} samples, 200 epochs, {n_joints} joints)...")
    t0 = __import__('time').time()
    best_loss, _, x_scaler, y_scaler = s5e.train_model(
        model, train_data, bases_rot, n_epochs=200, batch_size=32, lr=1e-3, device=device)
    print(f"Training: {__import__('time').time()-t0:.1f}s  best={best_loss:.4f}")

    # Test data — use rotation data for generate_motion
    if good_data is not None:
        test = good_data
    else:
        test = data[perm[170]]
    rot_test = test[:96, :72].reshape(96, n_joints, 3)
    tr_test = test[:96, 72:75]

    generated_24 = s5e.generate_motion(model, bases_rot, rot_test[0], rot_test[-1], tr_test,
                                        x_scaler=x_scaler, y_scaler=y_scaler,
                                        n_frames=96, device=device)

    true_24 = fk_smpl_full(rot_test.reshape(96, 72), tr_test)

    # ---- Animation ----
    out = Path(f"outputs/stage5e_walk_{N_BASE}base_perjoint.gif")
    out.parent.mkdir(parents=True, exist_ok=True)

    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    HALF = 1.4

    # Color-code: legs=blue, arms=green, spine=gray, head=red, hands=orange
    LEG_BONES = {(1,4),(4,7),(7,10),(2,5),(5,8),(8,11)}
    ARM_BONES = {(13,16),(16,18),(18,20),(14,17),(17,19),(19,21)}
    HAND_BONES = {(20,22),(21,23)}
    # Fixed: removed artificial (1,2) L_hip↔R_hip bone
    SPINE_BONES = {(0,1),(0,2),(0,3),(3,6),(6,9),(9,12),(12,15)}
    COLLAR_BONES = {(9,13),(9,14)}

    def bone_color(a, b):
        if (a,b) in LEG_BONES: return '#2196F3'      # blue
        if (a,b) in ARM_BONES: return '#4CAF50'      # green
        if (a,b) in HAND_BONES: return '#FF9800'     # orange
        if (a,b) in SPINE_BONES: return '#9E9E9E'    # gray
        if (a,b) in COLLAR_BONES: return '#795548'   # brown
        return '#607D8B'  # blue-gray default

    def update(frame):
        ax.cla()
        j = generated_24[frame]    # generated (24, 3) — hands GENERATED
        tj = true_24[frame]        # true (24, 3)

        # TRUE skeleton — RED, offset BACKWARD (trailing behind walker)
        OFFSET = np.array([-0.6, 0.0, 0.0])
        tj_off = tj + OFFSET
        for a, b in BONES_24:
            ax.plot([tj_off[a,0], tj_off[b,0]], [tj_off[a,1], tj_off[b,1]], [tj_off[a,2], tj_off[b,2]],
                    color='#E53935', lw=2.5, alpha=0.90)
        for i in range(24):
            ax.scatter(tj_off[i,0], tj_off[i,1], tj_off[i,2], c='#E53935', s=20,
                      alpha=0.9, edgecolors='#B71C1C', linewidth=0.3)

        # GENERATED skeleton — BLUE, centered
        for a, b in BONES_24:
            ax.plot([j[a,0], j[b,0]], [j[a,1], j[b,1]], [j[a,2], j[b,2]],
                    color='#1565C0', lw=2.5, alpha=0.90)
        for i in range(24):
            ax.scatter(j[i,0], j[i,1], j[i,2], c='#1565C0', s=20,
                      alpha=0.9, edgecolors='#0D47A1', linewidth=0.3)

        c = j.mean(axis=0)
        ax.set_xlim(c[0]-HALF-0.3, c[0]+HALF+0.3)
        ax.set_ylim(c[1]-HALF, c[1]+HALF)
        ax.set_zlim(c[2]-HALF, c[2]+HALF)
        ax.set_box_aspect((1, 1, 1))
        ax.set_xlabel('Forward'); ax.set_ylabel('Side'); ax.set_zlabel('Up')
        ax.set_title(f'BLUE=Gen  RED=True (trailing)  Frame {frame+1}/96', fontsize=13)
        from matplotlib.lines import Line2D
        leg = [Line2D([0],[0],color='#1565C0',lw=2,label='Generated'),
               Line2D([0],[0],color='#E53935',lw=2,label='True')]
        ax.legend(handles=leg, loc='upper right', fontsize=9)

    anim = FuncAnimation(fig, update, frames=96, interval=120)
    anim.save(str(out), writer=PillowWriter(fps=8))
    plt.close()

    # Metrics on ALL 24 joints (hands now generated, not at rest)
    rmse = np.sqrt(np.mean((generated_24 - true_24)**2))
    gen_amp = np.std(generated_24, axis=0).mean()
    true_amp = np.std(true_24, axis=0).mean()

    print(f"\nSaved: {out}")
    print(f"RMSE (all 24 joints): {rmse:.4f}m")
    print(f"Articulation: {gen_amp/true_amp:.2f}x")
    print(f"Joints: 24 (incl. L_hand, R_hand — GENERATED by model)")

if __name__ == "__main__":
    main()
